
TOKEN = "5769470051:AAFKKuRK4lNSJ3fkfyCDgJGQWP_4_rFhHxk"
MYSQL_USER = "root"
MYSQL_PASSWORD = "Abc12345!"
MYSQL_DATABASE = "emoji_db"
MYSQL_HOST = "localhost"


MYSQL_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}"




REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
